services:
    MenAtWork\NewsMostReadBundle\EventListener\NewsListener:
        arguments:
            - "@MenAtWork\\NewsMostReadBundle\\Services\\NewsReadCountService"
            - "@database_connection"
        tags:
            - { name: contao.hook, hook: minutely, method: onHourly, priority: 10 }
            - { name: contao.hook, hook: parseArticles, method: onParseArticles, priority: 10 }
            - { name: contao.hook, hook: newsListFetchItems, method: onNewsListFetchItems, priority: 10 }
        public: true

